
name: Update Quote of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs the action every day at midnight UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch a random quote
        id: get_quote
        run: |
          curl -s https://api.quotable.io/random > quote.json
          QUOTE=$(jq -r '.content' quote.json)
          AUTHOR=$(jq -r '.author' quote.json)
          echo "::set-output name=quote::$QUOTE"
          echo "::set-output name=author::$AUTHOR"

      - name: Update README with the new quote
        run: |
          QUOTE=$(echo "${{ steps.get_quote.outputs.quote }}")
          AUTHOR=$(echo "${{ steps.get_quote.outputs.author }}")
          sed -i "s/> _Your quote will appear here._/> \"$QUOTE\" - $AUTHOR/" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update quote of the day"
          git push
